export let names = {
    Relaxolotl:'loves to relax',
    Lumberjacksolotl:'Cuts down trees',
    Maxolotl:"takes things TO THE MAX!!!!!",
    Attacksolotl:"Attacks people",
    Askolotl:"asks questions",
    Hacksolotl:"hacker",
    Saxolotl:"plays the saxophone",
    Axeolotl:"Favorite tool of LumberJacksolotl",
    Taxlolotl:"pays taxes",
    Laxolotl:"lazy",
    Collapsolotl:"collapses",
    Quacksolotl:"🦆",
    Whacksolotl:"ready to whack you",
    Syntaxolotl:"ERROR: INCORRECT SYNTAX",
    Horsebacksolotl:"Rides a horse",
    Facemaskolotl:"back off, virus!!!!!!!",
    Multitasksolotl:"Writing this while playing poker and watching TV",
    Kayaksolotl:"kayaks... Even though it can swim 🤔",
    Pickaxolotl:"mines diamonds",
    Paybacksolotl:"Ready to get revenge",
    Snacksolotl:"eat him whenever",
    AntiTaxolotl:"mortal enemy of Taxolotl",
    AntiVaxolotl:"Does all her important medical research on Facebook",
    Jetpacksolotl:"flies a jetpack"
}
