export let names = {
    relaxolotl:'loves to relax',
    lumberjacksolotl:'Cuts down trees',
    maxolotl:"takes things TO THE MAX!!!!!",
    Attacksolotl:"Attacks people",
    Askolotl:"asks questions",
    Hacksolotl:"hacker",
    Saxolotl:"plays the saxophone",
    Axeolotl:"Favorite tool of LumberJacksolotl",
    Taxlolotl:"pays taxes",
    Laxolotl:"lazy",
    Collapsolotl:"collapses",
    Quacksolotl:"🦆",
    Whacksolotl:"ready to whack you",
    Syntaxolotl:"ERROR: INCORRECT SYNTAX",
    Horsebacksolotl:"Rides a horse",
    Facemaskolotl:"back off, virus!!!!!!!",
    Multitasksolotl:"Writing this while playing poker and watching TV",
    Kayaksolotl:"kayaks... Even though it can swim 🤔",
    Pickaxolotl:"mines diamonds",
    Paybacksolotl:"Ready to get revenge",
}
